/** Development-only fixtures. This module is excluded from production by main.tsx. */
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Download, Moon, Plus, Search, Sun, Table2, Trash2, Wrench } from 'lucide-react';
import { Button, IconButton } from '../components/ui/button';
import { Avatar } from '../components/ui/avatar';
import { Badge } from '../components/ui/badge';
import { StatusBadge } from '../components/patterns/status-badge';
import { Skeleton } from '../components/ui/skeleton';
import { Spinner } from '../components/ui/spinner';
import { ProgressBar } from '../components/ui/progress';
import { Separator } from '../components/ui/separator';
import { Checkbox } from '../components/ui/checkbox';
import { Field } from '../components/ui/field';
import { Input, SearchInput } from '../components/ui/input';
import { RadioGroup } from '../components/ui/radio-group';
import { SimpleSelect } from '../components/ui/select';
import { Switch } from '../components/ui/switch';
import { Textarea } from '../components/ui/textarea';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogBody, DialogFooter } from '../components/ui/dialog';
import { Drawer, DrawerContent, DrawerHeader, DrawerBody, DrawerFooter } from '../components/ui/drawer';
import { Popover, PopoverTrigger, PopoverContent } from '../components/ui/popover';
import { Menu, MenuTrigger, MenuContent, MenuItem } from '../components/ui/dropdown-menu';
import { Tooltip } from '../components/ui/tooltip';
import { ConfirmDialog } from '../components/patterns/confirm-dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '../components/ui/tabs';
import { Segmented } from '../components/ui/segmented-control';
import { DataTable } from '../components/ui/data-table';
import { DefList } from '../components/patterns/definition-list';
import { EmptyState, ErrorState, NoPermissionState } from '../components/patterns/feedback-state';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '../components/ui/table';
import { Page } from '../components/layout/page';
import { ListToolbar } from '../components/layout/list-toolbar';
import { DetailSection } from '../components/layout/detail-section';
import { FormActions } from '../components/layout/form-actions';
import { MetricBand } from '../components/layout/metric-band';
import { WorkspaceSection } from '../components/layout/workspace-section';
import { WorkspaceSplit } from '../components/layout/workspace-split';
import { WorkspaceActions } from '../components/layout/workspace-actions';
import { Card, CardBody } from '../components/ui/card';
import { SectionHeader } from '../components/patterns/section-header';
import { PageHeader } from '../components/patterns/page-header';
import { StatCard } from '../components/patterns/stat-card';
import { Stepper } from '../components/patterns/stepper';
import { AdminSidebar } from '../components/patterns/admin-sidebar';
import { Breadcrumb } from '../components/patterns/breadcrumb';
import { ServiceStatusBadge, PriorityBadge, TenantStatusBadge, VisitorStatusBadge, MeterStatusBadge } from '../components/patterns/status-badge';
import { SERVICE_STATUS, SERVICE_PRIORITY, TENANT_STATUS, VISITOR_STATUS } from '../lib/meta';
import type { ServiceStatus, ServicePriority, TenantStatus, VisitorStatus } from '../data/types';
import { BarSeriesChart } from '../components/patterns/charts';
import { useSession } from '../store/session';
import './workbench.css';

const FIXTURES = [
  { id: 'DEMO-101', title: 'Air handling unit inspection', tenant: 'Sample Aero Labs', status: 'assigned' as ServiceStatus, priority: 'high' as ServicePriority, count: 8 },
  { id: 'DEMO-102', title: 'Meeting room lighting', tenant: 'Sample Robotics', status: 'in_progress' as ServiceStatus, priority: 'medium' as ServicePriority, count: 3 },
  { id: 'DEMO-103', title: 'Access reader diagnostics', tenant: 'Sample Aero Labs', status: 'waiting_tenant' as ServiceStatus, priority: 'critical' as ServicePriority, count: 12 },
  { id: 'DEMO-104', title: 'Water pressure inspection', tenant: 'Sample Telemetry', status: 'resolved' as ServiceStatus, priority: 'low' as ServicePriority, count: 1 },
];
const SERIES = [{ label: 'Mon', kwh: 420 }, { label: 'Tue', kwh: 510 }, { label: 'Wed', kwh: 480 }, { label: 'Thu', kwh: 590 }, { label: 'Fri', kwh: 530 }, { label: 'Sat', kwh: 260 }, { label: 'Sun', kwh: 190 }];
const TOKENS = ['canvas', 'background', 'surface', 'surface-raised', 'surface-overlay', 'border', 'foreground', 'primary', 'success', 'warning', 'critical', 'info'];
const CHOICES = [{ value: 'email', label: 'Email' }, { value: 'portal', label: 'Portal' }, { value: 'disabled', label: 'Unavailable', disabled: true }];

function Example({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  return <section className="wb-example"><SectionHeader title={title} description={description} /><div className="wb-example-body">{children}</div></section>;
}
export default function DesignWorkbench() {
  const { prefs, setPrefs, toast } = useSession();
  const [checked, setChecked] = useState(true), [enabled, setEnabled] = useState(true);
  const [choice, setChoice] = useState('email'), [mode, setMode] = useState('list');
  const [name, setName] = useState(''), [note, setNote] = useState(''), [attempted, setAttempted] = useState(false);
  const [formSaved, setFormSaved] = useState(false), [dialog, setDialog] = useState(false), [drawer, setDrawer] = useState(false);
  const [confirm, setConfirm] = useState(false), [failConfirm, setFailConfirm] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [detail, setDetail] = useState(FIXTURES[0]);
  const [records, setRecords] = useState(FIXTURES), [search, setSearch] = useState('');
  const [selected, setSelected] = useState(new Set<string>()), [state, setState] = useState('ready');
  const rows = records.filter(row => `${row.title} ${row.tenant}`.toLowerCase().includes(search.toLowerCase()));
  return <Page workspace className="workbench">
    <PageHeader eyebrow="Development only · Approved NASTP foundation" title="Design system" description="Real production components. Deterministic examples. One visual language."
      actions={<><Button asChild variant="ghost"><Link to="/admin">Dashboard<ArrowUpRight /></Link></Button><Button onClick={() => setPrefs({ theme: prefs.theme === 'dark' ? 'light' : 'dark' })}>{prefs.theme === 'dark' ? <Sun /> : <Moon />}{prefs.theme === 'dark' ? 'Light mode' : 'Dark mode'}</Button></>} />
    <Tabs defaultValue="components">
      <TabsList className="wb-nav" aria-label="Design system sections"><TabsTrigger value="foundations">Foundations</TabsTrigger><TabsTrigger value="components">Components</TabsTrigger><TabsTrigger value="patterns">Patterns</TabsTrigger><TabsTrigger value="layout">Layout</TabsTrigger></TabsList>
      <TabsContent value="foundations" className="wb-content">
        <Example title="Semantic palette" description="Same roles in both themes. Borders separate surfaces; shadows belong to overlays."><div className="wb-swatches">{TOKENS.map(token => <div key={token}><span style={{ background: `var(--${token})` }} /><code>{token}</code></div>)}</div></Example>
        <Example title="Typography & numeric hierarchy"><div className="wb-type"><h1>Operations overview.</h1><h2>Energy performance</h2><p>Body · 14px. Clear labels and comfortable line height.</p><small>Caption · 12px. Context stays readable.</small><strong className="tnum">43.87 <small>MWh</small></strong></div></Example>
        <Example title="Spacing, radius, motion & elevation" description="4 / 8 / 12 / 16 / 20 / 24 / 32 / 40px. Controls, surfaces and overlays use named geometry, motion and shadow tokens."><div className="wb-row">{[4,8,12,16,20,24,32,40].map(space => <div key={space} className="wb-space"><i style={{ width: space, height: space }} /><span>{space}</span></div>)}</div><div className="wb-foundation-samples"><span className="is-control">Control radius</span><span className="is-surface">Surface radius</span><span className="is-overlay">Overlay elevation</span><span className="is-motion">Motion · fast / standard</span></div></Example>
        <Example title="Data visualization" description="Sage is the primary series. Label units and periods; provide exact values."><BarSeriesChart data={SERIES} series={[{ key: 'kwh', label: 'Consumption (kWh)' }]} height={220} /></Example>
      </TabsContent>
      <TabsContent value="components" className="wb-content">
        <Example title="Actions" description="One Button implementation: explicit intent, consistent dimensions, real disabled and pending states."><div className="wb-row"><Button variant="primary"><Plus />Primary</Button><Button>Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="danger"><Trash2 />Destructive</Button><Button variant="success">Success</Button></div><div className="wb-row"><Button size="xs">Extra small</Button><Button size="sm">Small</Button><Button size="md">Medium</Button><Button size="lg">Large</Button><Button disabled>Disabled</Button><Button loading>Saving</Button></div><div className="wb-row" aria-label="Icon button states"><Tooltip content="Primary icon action"><IconButton label="Primary icon action" variant="primary"><Plus /></IconButton></Tooltip><Tooltip content="Default icon action"><IconButton label="Default icon action"><Download /></IconButton></Tooltip><Tooltip content="Outline icon action"><IconButton label="Outline icon action" variant="outline"><Search /></IconButton></Tooltip><Tooltip content="Ghost icon action"><IconButton label="Ghost icon action" variant="ghost"><Wrench /></IconButton></Tooltip><Tooltip content="Selected icon action"><IconButton label="Selected icon action" variant="ghost" selected><Table2 /></IconButton></Tooltip><IconButton label="Disabled icon action" disabled><Search /></IconButton><IconButton label="Loading icon action" loading><Search /></IconButton><IconButton label="Remove item" variant="danger"><Trash2 /></IconButton></div></Example>
        <Example title="Form controls" description="Labels, hints and errors are associated with the actual control. Native and Radix keyboard semantics are retained."><form noValidate onSubmit={event => { event.preventDefault(); setAttempted(true); if (name.trim() && note.trim()) { setFormSaved(true); toast({ title: 'Sample form saved', variant: 'success' }); } }}>
          <div className="wb-form-grid"><Field label="Organization" required hint="Use the registered organization name." error={attempted && !name.trim() ? 'Enter an organization name.' : undefined}><Input value={name} onChange={event => { setName(event.target.value); setFormSaved(false); }} placeholder="Organization name" /></Field><Field label="Delivery channel"><SimpleSelect value={choice} onChange={setChoice} options={CHOICES} /></Field><Field label="Disabled field"><Input value="Managed by administrator" disabled readOnly /></Field><Field label="Invalid field" error="This email address is incomplete."><Input defaultValue="name@" /></Field><Field label="Resolution note" required error={attempted && !note.trim() ? 'Describe what was done.' : undefined}><Textarea value={note} onChange={event => { setNote(event.target.value); setFormSaved(false); }} placeholder="Describe the completed work…" rows={3} /></Field><Field label="Contact preference"><RadioGroup value={choice} onChange={setChoice} options={CHOICES} /></Field></div>
          <div className="wb-row"><label className="wb-choice"><Checkbox checked={checked} onCheckedChange={value => setChecked(value === true)} />Notify tenant</label><label className="wb-choice"><Checkbox checked="indeterminate" disabled />Partial selection</label><label className="wb-choice"><Checkbox disabled />Unavailable</label><label className="wb-choice"><Switch checked={enabled} onCheckedChange={setEnabled} />Live updates</label><Switch aria-label="Disabled switch" disabled /></div>
          <FormActions message={formSaved ? 'Saved locally in this example.' : 'Example values never enter production data.'}><Button variant="ghost" onClick={() => { setName(''); setNote(''); setAttempted(false); setFormSaved(false); }}>Reset example</Button><Button type="submit" variant="primary">Save example</Button></FormActions>
        </form></Example>
        <Example title="Identity & feedback"><div className="wb-row"><Avatar name="Ayesha Khan" /><Avatar name="Bilal Ahmed" size={28} /><Badge>Neutral badge</Badge><Badge tone="outline">Outline</Badge><StatusBadge tone="success">Operational</StatusBadge><StatusBadge tone="warning">Needs review</StatusBadge><StatusBadge tone="critical">Action required</StatusBadge><Spinner /><Skeleton className="h-5 w-28" /></div><ProgressBar value={62} /><Separator /><div className="wb-row"><Button onClick={() => toast({ title: 'Changes saved', description: 'This is the production toast.', variant: 'success' })}>Success toast</Button><Button onClick={() => toast({ title: 'Could not save', description: 'Your changes are retained. Try again.', variant: 'critical' })}>Error toast</Button><Segmented value={mode} onChange={setMode} options={[{value:'list',label:'List'},{value:'table',label:'Table'},{value:'unavailable',label:'Unavailable',disabled:true}]} /></div></Example>
        <Example title="Overlays" description="Dialog for a focused decision; drawer for contextual details; popover for a short picker."><div className="wb-row">
          <Dialog open={dialog} onOpenChange={setDialog}><DialogTrigger asChild><Button>Open dialog</Button></DialogTrigger><DialogContent size="sm"><DialogHeader title="Edit sample organization" description="A focused edit using the production dialog." /><DialogBody><Field label="Name"><Input defaultValue="Sample Aero Labs" /></Field></DialogBody><DialogFooter><Button variant="ghost" onClick={() => setDialog(false)}>Cancel</Button><Button variant="primary" onClick={() => { setDialog(false); toast({title:'Sample saved',variant:'success'}); }}>Save</Button></DialogFooter></DialogContent></Dialog>
          <Button onClick={() => setDrawer(true)}>Open drawer</Button>
          <Popover><PopoverTrigger asChild><Button>Open popover</Button></PopoverTrigger><PopoverContent aria-label="Notification preferences"><Field label="Notifications"><Switch checked={enabled} onCheckedChange={setEnabled} /></Field></PopoverContent></Popover>
          <Menu><MenuTrigger asChild><Button>Open menu</Button></MenuTrigger><MenuContent><MenuItem onSelect={() => toast({title:'Sample notification',variant:'info'})}>Show sample notification</MenuItem><MenuItem disabled>Unavailable action</MenuItem><MenuItem destructive onSelect={() => setConfirm(true)}>Remove sample</MenuItem></MenuContent></Menu>
          <Button variant="danger" onClick={() => setConfirm(true)}>Confirm removal</Button><label className="wb-choice"><Checkbox checked={failConfirm} onCheckedChange={value => setFailConfirm(value === true)} />Simulate save failure</label>
        </div></Example>
      </TabsContent>
      <TabsContent value="patterns" className="wb-content">
        <Example title="Application navigation" description="The shell and each navigation group collapse independently. Active modules and pages have distinct states."><div className="wb-sidebar-preview"><AdminSidebar badges={{alerts:4,overstaying:3,openRequests:78,notifications:11}} collapsed={sidebarCollapsed} onToggle={() => setSidebarCollapsed(value => !value)} pathname="/admin/energy/billing" /></div></Example>
        <Example title="Breadcrumb navigation" description="Ancestors are links; the current page is announced and remains non-interactive."><Breadcrumb items={[{label:'Workspace',to:'/admin'},{label:'Energy',to:'/admin/energy'},{label:'Charges & Billing'}]} /></Example>
        <Example title="List workspace" description="Keyboard sorting, pagination, selection, filtering, empty/loading/error states."><Segmented value={state} onChange={setState} options={['ready','loading','error','empty'].map(value => ({value,label:value}))} /><ListToolbar summary={`${rows.length} sample records`} onReset={search ? () => setSearch('') : undefined}><SearchInput value={search} onChange={setSearch} placeholder="Search sample records…" /></ListToolbar><DataTable rows={state === 'empty' ? [] : rows} loading={state === 'loading'} error={state === 'error' ? 'Example connection interrupted.' : undefined} onRetry={() => setState('ready')} rowKey={row => row.id} rowLabel={row => row.id} label="Sample service requests" pageSize={3} resetKey={search} selection={selected} onSelectionChange={setSelected} onRowClick={row => { setDetail(row); setDrawer(true); }} bulkActions={<Button size="xs" variant="danger" onClick={() => setConfirm(true)}>Remove selected samples</Button>} emptyTitle="No sample records match" emptyDescription="Try a different search or restore the examples." emptyAction={<Button onClick={() => {setSearch('');setState('ready');setRecords(FIXTURES);}}>Restore examples</Button>} columns={[{key:'title',header:'Request',cell:row=><div><strong className="font-medium text-foreground">{row.title}</strong><p className="text-xs text-subtle">{row.tenant}</p></div>,sortValue:row=>row.title},{key:'priority',header:'Priority',cell:row=><PriorityBadge priority={row.priority} />,sortValue:row=>row.count},{key:'status',header:'Status',cell:row=><ServiceStatusBadge status={row.status} />}]} /></Example>
        <Example title="Operational metrics"><div className="ds-metrics"><StatCard variant="inline" label="Active tenants" value="15" unit="/ 22" caption="4 pending · 1 suspended" /><StatCard variant="inline" label="Current load" value="594" unit="kW" caption="Fixture, not live data" /><StatCard variant="inline" label="Open requests" value="72" caption="7 critical" /><StatCard variant="inline" label="Waiting" value="12" caption="On tenant response" /></div></Example>
        <div className="wb-grid"><Card><CardBody><EmptyState title="No requests yet" description="Start with a clear next action." action={<Button onClick={() => toast({title:'Example action',variant:'info'})}><Plus />Example action</Button>} /></CardBody></Card><ErrorState message="Example connection unavailable." onRetry={() => toast({title:'Retry requested',variant:'info'})} /><NoPermissionState /><DetailSection title="Metadata"><DefList items={[{label:'Organization',value:'Sample Aero Labs'},{label:'Service status',value:<ServiceStatusBadge status="waiting_tenant" />},{label:'Priority',value:<PriorityBadge priority="high" />},{label:'Assignee',value:'Sample technician'}]} /></DetailSection></div>
        <Example title="NASTP domain status" description="Lifecycle labels and tones come from lib/meta.ts and the canonical status-badge pattern."><Table aria-label="Service lifecycle"><TableHeader><TableRow><TableHead>State</TableHead><TableHead>Production badge</TableHead></TableRow></TableHeader><TableBody>{(Object.keys(SERVICE_STATUS) as ServiceStatus[]).map(status => <TableRow key={status}><TableCell><code>{status}</code></TableCell><TableCell><ServiceStatusBadge status={status} /></TableCell></TableRow>)}</TableBody></Table><div className="wb-row">{(Object.keys(SERVICE_PRIORITY) as ServicePriority[]).map(priority => <PriorityBadge key={priority} priority={priority} />)}{(Object.keys(TENANT_STATUS) as TenantStatus[]).map(status => <TenantStatusBadge key={status} status={status} />)}{(Object.keys(VISITOR_STATUS) as VisitorStatus[]).map(status => <VisitorStatusBadge key={status} status={status} />)}<MeterStatusBadge status="online" /><MeterStatusBadge status="offline" /><MeterStatusBadge status="degraded" /></div></Example>
      </TabsContent>
      <TabsContent value="layout" className="wb-content">
        <Example title="Analytics workspace" description="Integrated metric cells and analytical regions share edges and dividers."><div className="wb-layout-frame"><MetricBand columns={3}><StatCard variant="inline" label="Current load" value="594" unit="kW" /><StatCard variant="inline" label="Period usage" value="49.3" unit="MWh" /><StatCard variant="inline" label="Peak demand" value="821" unit="kW" /></MetricBand><WorkspaceSplit ratio="wide"><WorkspaceSection title="Consumption over time" description="Primary analytical region"><BarSeriesChart data={SERIES} series={[{ key: 'kwh', label: 'Consumption (kWh)' }]} height={180} /></WorkspaceSection><WorkspaceSection title="Context" description="Supporting operational values"><DefList items={[{label:'Active meters',value:'57 / 59'},{label:'Offline',value:<StatusBadge tone="critical">2 meters</StatusBadge>}]} /></WorkspaceSection></WorkspaceSplit></div></Example>
        <Example title="Data workspace" description="Header actions, filters, rows and pagination form one continuous data surface."><div className="wb-layout-frame"><PageHeader eyebrow="Data workspace" title="Visitor history" description="Representative integrated list composition." actions={<Button size="sm"><Download />Export</Button>} /><ListToolbar summary="4 sample records"><SearchInput value={search} onChange={setSearch} placeholder="Search records…" /></ListToolbar><DataTable rows={rows} rowKey={row=>row.id} label="Workspace example" pageSize={3} columns={[{key:'title',header:'Record',cell:row=>row.title},{key:'tenant',header:'Organization',cell:row=>row.tenant},{key:'status',header:'Status',cell:row=><ServiceStatusBadge status={row.status} />}]} /></div></Example>
        <Example title="Operational workspace" description="A summary strip and flat triage rows keep severity and actions easy to scan."><div className="wb-layout-frame"><MetricBand columns={3}><StatCard variant="inline" label="Active" value="5" /><StatCard variant="inline" label="Critical" value="2" /><StatCard variant="inline" label="Acknowledged" value="3" /></MetricBand><WorkspaceSection title="Operations queue" description="Flat rows with shared separators" inset={false}><div className="ds-flat-list">{FIXTURES.slice(0,3).map(row=><div className="ds-operational-row" key={row.id}><div><strong>{row.title}</strong><p>{row.tenant} · {row.id}</p></div><div className="wb-row"><PriorityBadge priority={row.priority} /><Button size="xs">Open</Button></div></div>)}</div></WorkspaceSection></div></Example>
        <Example title="Setup workspace" description="Progress, form content, persistent context and predictable actions share one workspace."><div className="wb-layout-frame"><div className="ds-setup-progress"><Stepper steps={[{label:'Organization'},{label:'Configuration'},{label:'Review'}]} current={1} /></div><WorkspaceSplit ratio="wide"><WorkspaceSection title="Organization details"><div className="wb-form-grid"><Field label="Organization"><Input defaultValue="Sample Aero Labs" /></Field><Field label="Contact email"><Input defaultValue="ops@example.test" /></Field></div></WorkspaceSection><WorkspaceSection title="Setup context"><DefList items={[{label:'Plan',value:'Operations'},{label:'Status',value:<StatusBadge tone="warning">Draft</StatusBadge>}]} /></WorkspaceSection></WorkspaceSplit><WorkspaceActions message="Workbench fixture only"><Button variant="ghost">Cancel</Button><Button variant="primary">Continue</Button></WorkspaceActions></div></Example>
        <Example title="Detail workspace" description="Entity identity, status, structured sections and contextual actions remain aligned."><div className="wb-layout-frame"><PageHeader eyebrow="Service request · DEMO-101" title="Air handling unit inspection" description="Sample Aero Labs" actions={<ServiceStatusBadge status="assigned" />} /><WorkspaceSplit ratio="wide"><WorkspaceSection title="Request details"><DefList items={[{label:'Priority',value:<PriorityBadge priority="high" />},{label:'Location',value:'Building A · Level 2'},{label:'Assignee',value:'Facilities team'}]} /></WorkspaceSection><WorkspaceSection title="Actions"><div className="wb-row"><Button variant="primary">Start work</Button><Button variant="outline">Reassign</Button></div></WorkspaceSection></WorkspaceSplit></div></Example>
      </TabsContent>
    </Tabs>
          <Drawer open={drawer} onOpenChange={setDrawer}><DrawerContent><DrawerHeader title={detail.title} subtitle={`${detail.id} · ${detail.tenant}`} badge={<ServiceStatusBadge status={detail.status} />} /><DrawerBody><DetailSection title="Request details"><DefList items={[{label:'Category',value:'HVAC'},{label:'Location',value:'Sample building, room 101'}]} /></DetailSection><DetailSection title="Activity"><p className="text-sm text-muted">Assigned to the facilities team. Workbench fixture only.</p></DetailSection></DrawerBody><DrawerFooter><Button onClick={() => setDrawer(false)}>Close detail</Button></DrawerFooter></DrawerContent></Drawer>
    <ConfirmDialog open={confirm} onOpenChange={setConfirm} title="Remove sample records?" description="Removes selected examples, or the first example when none are selected. Only local workbench data is affected." confirmLabel="Remove samples" destructive onConfirm={async () => { await new Promise(resolve => setTimeout(resolve,400)); if (failConfirm) throw new Error('Example save failed. Turn off Simulate save failure and retry.'); setRecords(current=>current.filter((row,index)=>selected.size ? !selected.has(row.id) : index !== 0));setSelected(new Set());toast({title:'Sample records removed',variant:'success'}); }} />
    <footer className="wb-footer"><Wrench size={14} /> Development workbench · fixtures stay local <Download size={14} /> Production components, no separate demo library</footer>
  </Page>;
}
